// Blocks
export type {
    BaseBlock,
    Block,
    BlockStyles,
    BlockType,
    BlockVisibility,
    ButtonBlock,
    ColumnLayout,
    CountdownBlock,
    CustomBlock,
    DividerBlock,
    HtmlBlock,
    ImageBlock,
    MenuBlock,
    MenuItemData,
    ResponsiveStyles,
    SectionBlock,
    SocialIcon,
    SocialIconSize,
    SocialIconStyle,
    SocialIconsBlock,
    SocialPlatform,
    SpacerBlock,
    SpacingValue,
    TableBlock,
    TableCellData,
    TableRowData,
    TextBlock,
    VideoBlock,
} from './blocks';

// Type guards
export {
    isButton,
    isCountdown,
    isCustomBlock,
    isDivider,
    isHtml,
    isImage,
    isMenu,
    isSection,
    isSocialIcons,
    isSpacer,
    isTable,
    isText,
    isVideo,
} from './guards';

// Template
export type { TemplateContent, TemplateSettings } from './template';
export { createDefaultTemplateContent } from './template';

// Custom blocks
export type {
    CustomBlockBooleanField,
    CustomBlockColorField,
    CustomBlockDefinition,
    CustomBlockField,
    CustomBlockFieldBase,
    CustomBlockFieldType,
    CustomBlockImageField,
    CustomBlockNumberField,
    CustomBlockRepeatableField,
    CustomBlockSelectField,
    CustomBlockTextField,
    CustomBlockTextareaField,
    DataSourceConfig,
    DataSourceFetchContext,
    SelectOption,
} from './custom-blocks';

// Block factory
export {
    cloneBlock,
    createBlock,
    createButtonBlock,
    createCountdownBlock,
    createCustomBlock,
    createDividerBlock,
    createHtmlBlock,
    createImageBlock,
    createMenuBlock,
    createSectionBlock,
    createSocialIconsBlock,
    createSpacerBlock,
    createTableBlock,
    createTextBlock,
    createVideoBlock,
    generateId,
} from './factory';

// Event emitter
export { EventEmitter } from './events';

// Merge tags
export type { SyntaxPreset, SyntaxPresetName } from './merge-tags';
export {
    containsMergeTag,
    getLogicMergeTagKeyword,
    getMergeTagLabel,
    isLogicMergeTagValue,
    isMergeTagValue,
    resolveHtmlLogicMergeTagLabels,
    resolveHtmlMergeTagLabels,
    resolveSyntax,
    restoreMergeTagMarkup,
    SYNTAX_PRESETS,
} from './merge-tags';

// Config
export type {
    CustomFont,
    DisplayCondition,
    DisplayConditionsConfig,
    ExportResult,
    FontsConfig,
    MergeTag,
    MergeTagsConfig,
    ThemeOverrides,
    ViewportSize,
} from './config';
export { SdkError } from './config';

// Cloud types (zero runtime cost — all type-only except re-exported ViewportSize/SyntaxPreset)
export type {
    AiChatMessage,
    AiConfig,
    AiGenerateOptions,
    AiScoreOptions,
    AiStreamEvent,
    ApiError,
    ApiResponse,
    AuthConfig,
    AuthRequestOptions,
    CategoryScore,
    Collaborator,
    CollaborationConfig,
    Comment,
    CommentEvent,
    CommentEventType,
    CommentThread,
    CreateCommentData,
    DirectAuthConfig,
    EditorState,
    FindingSeverity,
    HeadlessAuthConfig,
    HeadlessConfig,
    HeadlessEvents,
    HeadlessTemplaticalInstance,
    HealthCheckResult,
    McpConfig,
    McpOperation,
    McpOperationPayload,
    MediaBrowseParams,
    MediaBrowseResponse,
    MediaCategory,
    MediaCategoryData,
    MediaConfig,
    MediaConversion,
    MediaFolder,
    MediaItem,
    MediaRequestContext,
    MediaUsageInfo,
    MediaUsageResponse,
    PlanConfig,
    PlanFeatures,
    PlanLimits,
    ProxyAuthConfig,
    RewriteData,
    SavedModule,
    SaveResult,
    ScoringCategory,
    ScoringFinding,
    ScoringResult,
    StorageInfo,
    Template,
    TemplaticalConfig,
    TemplaticalInstance,
    TemplateSnapshot,
    TestEmailConfig,
    TokenData,
    UpdateCommentData,
    UserConfig,
    WebSocketServerConfig,
} from './cloud';
