/**
 * Which kind of file a listing or picker is constrained to.
 *
 * Image fields and the video thumbnail pass `["images"]`. Custom blocks may
 * pass other categories. The modal forces `list({ category })` to that set.
 */
export type MediaCategory = "images" | "documents" | "videos" | "audio";

/**
 * One file in a media library — the row `list` returns and `create` persists.
 *
 * Distinct from `MediaResult` in `./config` (`{ url, alt? }`): that is what
 * an image field stores. A picked asset is reduced to a result at confirm;
 * the library itself talks in assets.
 *
 * The store owns `id` — it is returned by {@link MediaProvider.create} and
 * never generated by the editor, so identity stays a property of your storage.
 *
 * There is no conversion set (`small` / `medium` / `large`) on this type. The
 * grid uses {@link thumbnailUrl} falling back to {@link url}; confirm always
 * inserts `url`. If a derivative belongs in the email, put that URL on `url`.
 */
export interface MediaAsset {
  /** Store-assigned. The editor never generates one. */
  id: string;
  /** The URL that lands on the block when the asset is confirmed. */
  url: string;
  alt?: string;
  filename?: string;
  mimeType?: string;
  width?: number;
  height?: number;
  /** Size in bytes. */
  size?: number;
  /**
   * Grid thumbnail. Falls back to {@link url} when omitted, so a store that
   * only has one URL still renders.
   */
  thumbnailUrl?: string;
  /** Folder this asset sits in, or `null` / omitted for the root. */
  folderId?: string | null;
  /**
   * Store-assigned timestamps, ISO 8601, used for display only. They do not
   * affect ordering — the editor renders whatever order `list()` returns.
   */
  createdAt?: string;
  updatedAt?: string;
  /**
   * Per-entry permission carve-outs. **Absent means allowed** — the provider's
   * `update` / `delete` already say whether the capability exists at all, so
   * these exist only to forbid it on *particular* entries.
   *
   * They compose one-way: `canUpdate: true` cannot re-enable an `update: false`.
   */
  canUpdate?: boolean;
  canDelete?: boolean;
}

/**
 * One folder in the library. {@link MediaFoldersProvider.list} returns these
 * **flat**; the UI trees them via {@link parentId}.
 */
export interface MediaFolder {
  id: string;
  name: string;
  /** `null` / omitted = root. */
  parentId?: string | null;
}

/**
 * Parameters for {@link MediaProvider.list}.
 *
 * Unlike saved-blocks (which the editor calls bare and filters in memory),
 * these are **real**: galleries outgrow one response, so search, folder,
 * category and cursor are sent on every listing. A provider that ignores them
 * cannot page or search.
 *
 * `templateId` is opportunistic — present when a template is loaded, omitted
 * on a blank canvas. Cloud's store ignores it; a CMS that scopes a gallery
 * per template reads it here.
 */
export interface MediaListParams {
  search?: string;
  cursor?: string;
  folderId?: string | null;
  category?: MediaCategory;
  /** When a template is loaded; Cloud ignores. */
  templateId?: string;
}

/**
 * One page of {@link MediaProvider.list}.
 *
 * An envelope rather than a bare array so pagination never needs a breaking
 * change: a cursor has somewhere to live from day one. A provider that returns
 * everything at once omits {@link nextCursor}.
 */
export interface MediaListPage {
  items: MediaAsset[];
  nextCursor?: string;
}

/**
 * How many templates reference an asset, for the bulk-delete warning.
 *
 * Returned from {@link MediaProvider.checkUsage} keyed by asset id.
 */
export interface MediaUsageInfo {
  templateCount: number;
  templateNames: string[];
}

/**
 * Quota snapshot for the storage ring. `storage()` may resolve `null` when
 * the store does not track quota (or, for Cloud, until plan config has loaded).
 */
export interface MediaStorageInfo {
  usedBytes: number;
  limitBytes: number;
}

/**
 * Why the media picker opened. Passed to `onRequestMedia` and used by the
 * modal to constrain the listing.
 *
 * `files` is the drop path: image files dragged onto an image block. Absent
 * on click → Browse.
 */
export interface MediaRequestContext {
  accept?: MediaCategory[];
  /** Drop path; absent on Browse. */
  files?: File[];
}

/** Payload for {@link MediaProvider.create}. */
export interface MediaCreateInput {
  file: File;
  folderId?: string | null;
  alt?: string;
  filename?: string;
  templateId?: string;
}

/**
 * Partial patch for {@link MediaProvider.update}. Only the keys present are
 * being changed.
 */
export interface MediaAssetPatch {
  alt?: string;
  filename?: string;
}

/** Payload for {@link MediaFoldersProvider.create}. */
export interface MediaFolderInput {
  name: string;
  parentId?: string | null;
}

/**
 * Nested folder + move contract, so an OSS gallery writes `folders: false`
 * once rather than stubbing five methods.
 *
 * `list` returns a **flat** array; the UI trees it via {@link MediaFolder.parentId}.
 * A store whose HTTP API returns a tree flattens it here.
 */
export interface MediaFoldersProvider {
  /** Flat listing. The one method that cannot be `false` when folders exist. */
  list(): Promise<MediaFolder[]>;
  create: false | ((input: MediaFolderInput) => Promise<MediaFolder>);
  update:
    false | ((id: string, patch: { name: string }) => Promise<MediaFolder>);
  delete: false | ((id: string) => Promise<void>);
  /**
   * Move assets into a folder (`folderId: null` = root) and return the stored
   * results. Bulk — the grid is multi-select.
   */
  move:
    false | ((ids: string[], folderId: string | null) => Promise<MediaAsset[]>);
}

/**
 * Configuration and outward notifications for the media library. Every member
 * is optional.
 *
 * Separate from the storage methods so `initCloud()` can accept this half
 * alone: these fire the same way whichever store holds the assets, Cloud's
 * own or yours. {@link MediaProvider} extends this, so one object satisfies
 * both entry points.
 *
 * `maxFileSize` / `mimeTypes` are a **client pre-check**, not a security
 * boundary — the backend must enforce too.
 */
export interface MediaOptions {
  /** Bytes; client pre-check only. */
  maxFileSize?: number;
  mimeTypes?: Partial<Record<MediaCategory, string[]>>;
  /** An asset was created and prepended to the listing. */
  onCreated?: (asset: MediaAsset) => void;
  /** An asset was updated and its listing entry replaced. */
  onUpdated?: (asset: MediaAsset) => void;
  /**
   * An asset was deleted and filtered out of the listing. `delete` resolves
   * to nothing, so this carries the entry the editor captured before removing
   * it — not an id.
   *
   * Fires only when the entry was present in the locally loaded list at the
   * time of the delete. Deleting an id that was never loaded still deletes
   * successfully; there is just nothing to pass, so this does not fire.
   */
  onDeleted?: (asset: MediaAsset) => void;
}

/**
 * Storage contract for a media library. Implement it to back the editor's
 * media picker with your own persistence — the editor owns the modal, the
 * grid, crop (client-side; persisting a crop is `create` or `replace` of the
 * resulting `File`) and insertion; you own the transport.
 *
 * Pass an implementation as `media` to `init()`. When omitted, the feature
 * stays off entirely and image fields are URL-only. `onRequestMedia` remains
 * the UI override (a host widget); it is not this store.
 *
 * Every method may reject; the editor surfaces the failure through `onError`
 * and leaves its in-memory list untouched. Provider messages are
 * user-presentable.
 *
 * **Each method other than `list` can be turned off by passing `false`
 * instead of a function.** The editor then hides the affordance rather than
 * letting the user try and fail. They are required rather than optional
 * precisely so that disabling is a decision you state, never something you
 * get by forgetting a method. Setting every mutation to `false` yields a
 * **read-only library**: users still browse, search and pick, because picking
 * only copies a URL onto the canvas.
 *
 * `list` cannot be `false`: without it there is nothing to show.
 *
 * ```ts
 * const media: MediaProvider = {
 *   list: ({ search, cursor, templateId }) =>
 *     myCms.page({ search, cursor, templateId }),
 *   create: ({ file }) => myCms.upload(file),
 *   update: false,
 *   delete: false,
 *   folders: false,
 *   replace: false,
 *   importFromUrl: false,
 *   checkUsage: false,
 *   frequentlyUsed: false,
 *   storage: false,
 * };
 * ```
 */
export interface MediaProvider extends MediaOptions {
  /**
   * Fetch one page of assets. Search, folder, category and cursor are real
   * params — this is not an in-memory filter over a full dump.
   *
   * The one method that cannot be disabled: without it the feature has nothing
   * to show.
   */
  list(params?: MediaListParams): Promise<MediaListPage>;
  /**
   * Persist a new asset from a `File` and return it with its store-assigned
   * `id`, or `false` to disable upload — the drop zone and upload control then
   * do not render. There is no progress callback; resolve with the asset.
   */
  create: false | ((input: MediaCreateInput) => Promise<MediaAsset>);
  /**
   * Apply a partial update and return the stored result, or `false` to disable
   * editing entirely. Per-entry exceptions go through
   * {@link MediaAsset.canUpdate}.
   */
  update: false | ((id: string, patch: MediaAssetPatch) => Promise<MediaAsset>);
  /**
   * Remove assets by id, resolving once the store has applied the delete, or
   * `false` to disable deletion entirely. **Bulk** — the grid is multi-select.
   * Per-entry exceptions go through {@link MediaAsset.canDelete}.
   */
  delete: false | ((ids: string[]) => Promise<void>);
  /**
   * Folder tree + move, or `false` to hide folders entirely. Nested so a
   * gallery without folders writes `folders: false` once.
   */
  folders: false | MediaFoldersProvider;
  /**
   * Replace an asset's file in place and return the stored result, or `false`
   * to disable replace.
   */
  replace: false | ((id: string, file: File) => Promise<MediaAsset>);
  /**
   * Import a remote URL into the library and return the stored asset, or
   * `false` to hide import. `folderId` / `templateId` are the same opportunistic
   * scoping as {@link MediaCreateInput}.
   */
  importFromUrl:
    | false
    | ((
        url: string,
        folderId?: string | null,
        templateId?: string,
      ) => Promise<MediaAsset>);
  /**
   * Look up how many templates reference each asset, or `false` to skip the
   * usage warning on delete. **Bulk** — keyed by the same id array `delete`
   * takes.
   */
  checkUsage:
    false | ((ids: string[]) => Promise<Record<string, MediaUsageInfo>>);
  /**
   * Assets the current user reaches for often, or `false` to hide that tab.
   */
  frequentlyUsed: false | (() => Promise<MediaAsset[]>);
  /**
   * Current quota, or `false` to hide the storage ring. May resolve `null`
   * when the store does not (yet) know.
   */
  storage: false | (() => Promise<MediaStorageInfo | null>);
}
