import type { TemplateContent } from "./template";

/**
 * A stored template: its identity, an optional human-readable name, and the
 * content the editor edits.
 *
 * The store owns `id` — it is returned by {@link TemplatesProvider.create} and
 * never generated by the editor, so identity stays a property of your storage
 * (database primary key, slug, document id).
 */
export interface Template {
  id: string;
  /**
   * Optional display name, shown in the editor header and editable inline.
   *
   * Optional because a store may not have a name column, in which case the
   * header renders nothing to edit. A rename is persisted as an ordinary
   * `save(id, { name })` patch — there is no separate rename method.
   */
  name?: string;
  content: TemplateContent;
}

/**
 * Partial patch for {@link TemplatesProvider.save}. Only the keys present are
 * being changed, so a rename can travel without content and vice versa.
 *
 * A patch (rather than bare content) because retrofitting `save(id, content)`
 * into `save(id, patch)` later would break every implementation — the same
 * reasoning, and the same shape, as `SavedBlockPatch`.
 */
export type TemplatePatch = Partial<{
  name: string;
  content: TemplateContent;
}>;

/**
 * Storage contract for the template itself — the save/load lifecycle around
 * whatever the editor is editing.
 *
 * Deliberately **not** CRUD: there is no `list` and no `delete`, and the editor
 * has no template browser. Choosing *which* template to open belongs to your
 * own application, which then hands the id to `editor.load(id)`.
 *
 * Pass an implementation as `templates` to `init()`. When omitted, the header's
 * name field, save button and save-status indicator do not render, and
 * `create()` / `load()` / `save()` reject with an explanatory error.
 *
 * Every method may reject; the editor reports the failure through `onError`,
 * surfaces it in the header, and leaves its state untouched — nothing is marked
 * saved that wasn't.
 *
 * **Each mutation can be turned off by passing `false` instead of a function**,
 * mirroring `SavedBlocksProvider`. They are required rather than optional
 * precisely so that disabling is a decision you state, never something you get
 * by forgetting a method. `save: false` yields a genuine read-only mode (a
 * template still loads and can be edited locally, there is simply nothing to
 * persist); `create: false` yields a no-new-templates mode.
 *
 * ```ts
 * const provider: TemplatesProvider = {
 *   load: (id) => fetch(`/api/templates/${id}`).then((r) => r.json()),
 *   create: (input) =>
 *     fetch("/api/templates", {
 *       method: "POST",
 *       headers: { "Content-Type": "application/json" },
 *       body: JSON.stringify(input),
 *     }).then((r) => r.json()),
 *   save: (id, patch) =>
 *     fetch(`/api/templates/${id}`, {
 *       method: "PATCH",
 *       headers: { "Content-Type": "application/json" },
 *       body: JSON.stringify(patch),
 *     }).then((r) => r.json()),
 * };
 * ```
 */
export interface TemplatesProvider {
  /**
   * Fetch a template by id. The one method that cannot be disabled: without it
   * there is nothing to open.
   */
  load(id: string): Promise<Template>;
  /**
   * Persist a new template and return it with its store-assigned `id`, or
   * `false` to disable creation entirely.
   */
  create:
    | false
    | ((input: {
        name?: string;
        content: TemplateContent;
      }) => Promise<Template>);
  /**
   * Apply a partial update to an existing template and return the stored
   * result, or `false` to disable saving entirely — the editor then hides both
   * the save button and the save-status indicator.
   */
  save: false | ((id: string, patch: TemplatePatch) => Promise<Template>);
}
