import type { TemplateContent } from "./template";

/**
 * A stored template: its identity, an optional human-readable name, and the
 * content the editor edits.
 *
 * The store owns `id` — it is returned by {@link TemplatesProvider.create} and
 * never generated by the editor, so identity stays a property of your storage
 * (database primary key, slug, document id).
 */
export interface Template {
  id: string;
  /**
   * Optional display name, shown in the editor header and editable inline.
   *
   * Optional because a store may not have a name column, in which case the
   * header renders nothing to edit. A rename is persisted as an ordinary
   * `save(id, { name })` patch — there is no separate rename method.
   */
  name?: string;
  /**
   * When your store created the template, ISO 8601.
   *
   * A fallback for {@link Template.updatedAt}: the header prefers `updatedAt`
   * and reads this only in its absence, so a store that records creation but not
   * modification still shows something.
   */
  createdAt?: string;
  /**
   * When your store last wrote the template, ISO 8601.
   *
   * Display-only — the header renders it as a relative label ("Updated 5m ago")
   * with the absolute date on hover. Both timestamps are absent from
   * {@link TemplatePatch}, so the editor never writes them: they are yours to
   * set, and the value the editor shows is whatever `load` or `save` returned.
   * Absent, or a value that does not parse, renders nothing.
   */
  updatedAt?: string;
  content: TemplateContent;
}

/**
 * Partial patch for {@link TemplatesProvider.save}. Only the keys present are
 * being changed, so a rename can travel without content and vice versa.
 *
 * A patch (rather than bare content) because retrofitting `save(id, content)`
 * into `save(id, patch)` later would break every implementation — the same
 * reasoning, and the same shape, as `SavedBlockPatch`.
 */
export type TemplatePatch = Partial<{
  name: string;
  content: TemplateContent;
}>;

/**
 * Why a save happened, as reported to {@link TemplatesOptions.onSaved}.
 *
 * `manual` covers both the header's Save button and Cmd+S: one intent, and
 * splitting them would invite handling one and silently missing the other.
 *
 * The other three are separate because treating them as a Save press is wrong.
 * A `rename` writes through `save()` but the user only edited the name, and a
 * `restore` write is the confirmation step of restoring a version — navigating
 * away on either strands the user mid-task.
 */
export type TemplateSaveTrigger =
  "manual" | "autosave" | "rename" | "restore" | "api";

/**
 * Configuration and outward notifications for the template lifecycle. Every
 * member is optional.
 *
 * Separate from the storage methods so `initCloud()` can accept this half alone:
 * Cloud owns template storage, because the id it issues is the join key for
 * collaboration, version history, comments, AI rewrite, scoring and the
 * server-side export. {@link TemplatesProvider} extends this, so one object
 * satisfies both entry points and moving to Cloud edits nothing.
 */
export interface TemplatesOptions {
  /**
   * Save automatically, debounced, after the user stops editing.
   *
   * Lives here because it is meaningless without somewhere to save to. The
   * cadence is `changeDebounce` at the config root, since one timer drives both
   * this and the `onChange` notification, and `onChange` works with no provider.
   *
   * Defaults to off for `init()` and on for `initCloud()` — a Cloud session
   * always has a store.
   */
  autoSave?: boolean;
  /**
   * Warn before the tab closes with unsaved changes. Defaults to on.
   *
   * Cannot cover client-side route changes; `onDirtyChange` at the config root
   * is what guards a router, and it fires with or without a provider.
   */
  unsavedChangesGuard?: boolean;
  /**
   * Render the inline template-name field in the header. Defaults to on.
   *
   * `false` hides the field and nothing else: `create({ name })`, `setName()`
   * and the `name` in each save patch keep working, so your own chrome can still
   * manage names.
   */
  nameField?: boolean;
  /**
   * A save completed, with `isDirty` cleared and `isSaving` false — so a
   * handler may navigate without tripping the consumer's own unsaved-changes
   * guard. Never fires for a failed save; that reaches `onError`.
   *
   * `template` is the provider's response to `save()` as returned, not
   * necessarily what got adopted: a rename that lands mid-flight keeps the
   * local name, and under a concurrent `load()` it may describe a template
   * that is no longer open.
   */
  onSaved?: (
    template: Template,
    meta: { trigger: TemplateSaveTrigger },
  ) => void;
  /** A template was created and attached to the editor. */
  onCreated?: (template: Template) => void;
  /** A template was fetched and its content put on the canvas. */
  onLoaded?: (template: Template) => void;
}

/**
 * Storage contract for the template itself — the save/load lifecycle around
 * whatever the editor is editing.
 *
 * Deliberately **not** CRUD: there is no `list` and no `delete`, and the editor
 * has no template browser. Choosing *which* template to open belongs to your
 * own application, which then hands the id to `editor.load(id)`.
 *
 * Pass an implementation as `templates` to `init()`. When omitted, the header's
 * name field, save button and save-status indicator do not render, and
 * `create()` / `load()` / `save()` reject with an explanatory error.
 *
 * Every method may reject; the editor reports the failure through `onError`,
 * surfaces it in the header, and leaves its state untouched — nothing is marked
 * saved that wasn't.
 *
 * **Each mutation can be turned off by passing `false` instead of a function**,
 * mirroring `SavedBlocksProvider`. They are required rather than optional
 * precisely so that disabling is a decision you state, never something you get
 * by forgetting a method. `save: false` yields a genuine read-only mode (a
 * template still loads and can be edited locally, there is simply nothing to
 * persist); `create: false` yields a no-new-templates mode.
 *
 * ```ts
 * const provider: TemplatesProvider = {
 *   load: (id) => fetch(`/api/templates/${id}`).then((r) => r.json()),
 *   create: (input) =>
 *     fetch("/api/templates", {
 *       method: "POST",
 *       headers: { "Content-Type": "application/json" },
 *       body: JSON.stringify(input),
 *     }).then((r) => r.json()),
 *   save: (id, patch) =>
 *     fetch(`/api/templates/${id}`, {
 *       method: "PATCH",
 *       headers: { "Content-Type": "application/json" },
 *       body: JSON.stringify(patch),
 *     }).then((r) => r.json()),
 * };
 * ```
 */
export interface TemplatesProvider extends TemplatesOptions {
  /**
   * Fetch a template by id. The one method that cannot be disabled: without it
   * there is nothing to open.
   */
  load(id: string): Promise<Template>;
  /**
   * Persist a new template and return it with its store-assigned `id`, or
   * `false` to disable creation entirely.
   */
  create:
    | false
    | ((input: {
        name?: string;
        content: TemplateContent;
      }) => Promise<Template>);
  /**
   * Apply a partial update to an existing template and return the stored
   * result, or `false` to disable saving entirely — the editor then hides both
   * the save button and the save-status indicator.
   */
  save: false | ((id: string, patch: TemplatePatch) => Promise<Template>);
}
