import type { Component } from "vue";
import {
  AppWindow,
  Bookmark,
  Braces,
  CircleAlert,
  CodeXml,
  Eye,
  EyeOff,
  FileInput,
  FileText,
  GitBranch,
  History,
  Image,
  Languages,
  MessageSquare,
  MousePointerClick,
  Paintbrush,
  Palette,
  Puzzle,
  Send,
  Type,
} from "@lucide/vue";

export const SCENE_ICONS: Record<string, Component> = {
  fonts: Type,
  defaults: Palette,
  theming: Paintbrush,
  i18n: Languages,
  "shadow-dom-off": AppWindow,
  issues: CircleAlert,
  "custom-blocks": Puzzle,
  "merge-tags": Braces,
  "merge-tags-on-request": MousePointerClick,
  "merge-tags-samples": Eye,
  "merge-tags-resolve-preview": Eye,
  "logic-tags": GitBranch,
  "display-conditions": EyeOff,
  templates: FileText,
  "version-history": History,
  comments: MessageSquare,
  "saved-blocks": Bookmark,
  media: Image,
  "test-email": Send,
  render: CodeXml,
  "import-unlayer": FileInput,
  "import-beefree": FileInput,
  "import-html": FileInput,
  "import-mjml": FileInput,
  "import-topol": FileInput,
  "import-stripo": FileInput,
  "import-chamaileon": FileInput,
  "import-easy-email-pro": FileInput,
};
